CREATE TABLE jobs (
  id SERIAL PRIMARY KEY,
  company VARCHAR(255) NOT NULL,
  logo VARCHAR(255),
  title VARCHAR(255) NOT NULL,
  applicants INTEGER DEFAULT 0,
  tags TEXT[],
  salary VARCHAR(255),
  posted VARCHAR(255),
  "desc" TEXT,
  matchScore INTEGER,
  location VARCHAR(255),
  experience VARCHAR(255),
  type VARCHAR(255),
  level VARCHAR(255),
  deadline VARCHAR(255),
  responsibilities TEXT[],
  requirements TEXT[],
  benefits TEXT[]
);

INSERT INTO jobs (company, logo, title, applicants, tags, salary, posted, "desc", matchScore, location, experience, type, level, deadline, responsibilities, requirements, benefits)
VALUES 
(
  'MetaMask', 
  '🦊', 
  'Product Designer', 
  25, 
  ARRAY['Entry Level', 'Full-Time'], 
  '$250/hr', 
  '12 days ago', 
  'Doing the right thing for investors is what we''re all about at MetaMask. We believe design is at the heart of every great product, and we''re looking for a passionate Product Designer to help shape the future of decentralized finance. You will work closely with engineering, product, and research teams to craft intuitive and beautiful user experiences.', 
  98, 
  'San Francisco, CA (Remote)', 
  '1-3 years', 
  'Full-Time', 
  'Entry Level', 
  'June 30, 2026', 
  ARRAY['Design intuitive UI flows for web3 products', 'Collaborate with cross-functional teams', 'Conduct user research and usability testing', 'Create wireframes, prototypes, and high-fidelity designs', 'Maintain and evolve the design system'], 
  ARRAY['1+ years of product design experience', 'Proficiency in Figma or similar tools', 'Understanding of web3 or crypto a plus', 'Strong portfolio showcasing UX work', 'Excellent communication skills'], 
  ARRAY['Remote-first culture', 'Equity package', 'Health insurance', 'Learning & development budget', 'Flexible PTO']
),
(
  'Netflix', 
  '🎥', 
  'Sr. UX Designer', 
  14, 
  ARRAY['Expert', 'Part-Time', 'Remote'], 
  '$195/hr', 
  '5 days ago', 
  'Netflix is one of the world''s leading streaming entertainment services with 260 million paid memberships in over 190 countries. We are looking for a Senior UX Designer to join our content discovery team. You will be responsible for designing seamless experiences that help millions of users find the perfect show or movie.', 
  85, 
  'Los Gatos, CA (Remote)', 
  '5+ years', 
  'Part-Time', 
  'Expert', 
  'May 31, 2026', 
  ARRAY['Lead end-to-end design for content discovery features', 'Define UX strategy and design vision', 'Present design work to executive stakeholders', 'Mentor junior designers on the team', 'Drive A/B testing and iterative design improvements'], 
  ARRAY['5+ years of UX design experience', 'Track record of shipping large-scale products', 'Expertise in Figma, Protopie, and research tools', 'Strong analytical and data-driven mindset', 'Experience with streaming or media products'], 
  ARRAY['Unlimited vacation', 'Top-tier compensation', 'Netflix subscription', '401k matching', 'Parental leave']
),
(
  'Microsoft', 
  '🪟', 
  'AI Engineer', 
  58, 
  ARRAY['Intermediate', 'Full-Time'], 
  '$210/hr', 
  '4 days ago', 
  'Microsoft is at the forefront of AI innovation. We are building the next generation of intelligent tools that empower people and organizations. As an AI Engineer, you will work on cutting-edge machine learning models and integrate them into Microsoft''s suite of productivity products including Azure, Office 365, and Copilot.', 
  72, 
  'Redmond, WA (Hybrid)', 
  '3-5 years', 
  'Full-Time', 
  'Intermediate', 
  'July 15, 2026', 
  ARRAY['Design and train large-scale ML models', 'Integrate AI capabilities into Microsoft products', 'Collaborate with research scientists and product teams', 'Optimize model performance and inference speed', 'Write clean, maintainable production code'], 
  ARRAY['3+ years of ML/AI engineering experience', 'Proficiency in Python, PyTorch, or TensorFlow', 'Experience with cloud platforms (Azure preferred)', 'Knowledge of NLP or computer vision', 'Strong CS fundamentals'], 
  ARRAY['Hybrid work model', 'Azure credits', 'Employee stock purchase plan', 'Comprehensive health coverage', 'Tuition reimbursement']
),
(
  'Reddit', 
  '🤖', 
  'Data Scientist', 
  23, 
  ARRAY['Expert', 'Part-Time'], 
  '$120/hr', 
  '22 days ago', 
  'At Reddit, we help communities come together around shared interests, passions, and causes. As a Data Scientist, you will work with massive datasets to uncover insights about how our platform is used, power recommendation systems, and help teams make data-driven decisions that shape the Reddit experience for hundreds of millions of users.', 
  60, 
  'New York, NY (On-site)', 
  '5+ years', 
  'Part-Time', 
  'Expert', 
  'June 10, 2026', 
  ARRAY['Analyze large-scale user behavior datasets', 'Build and maintain recommendation algorithms', 'Partner with product and engineering teams', 'Design and analyze A/B experiments', 'Communicate findings to non-technical stakeholders'], 
  ARRAY['5+ years of data science experience', 'Strong proficiency in SQL, Python, and R', 'Experience with Spark or distributed computing', 'Background in statistics and experimentation', 'Communication and storytelling with data'], 
  ARRAY['Reddit Gold subscription', 'Annual bonus', 'Stock options', 'Wellness reimbursement', 'On-site gym']
);
